[SPARK-53554] Fix `sum_distinct`
### What changes were proposed in this pull request?
This PR aims to fix `sum_distinct`.
In the current spark-connect-rust, `sum_distinct` doesn't work correctly.
If we run the following code,

```
let df = spark
    .sql("SELECT * FROM VALUES (1), (2), (3), (1), (2), (3) AS data(value)")
    .await?;
df.select([sum_distinct(col("value")).alias("sum")])
    .show(None, None, None)
    .await?;
```

We will get the following error.
```
Error: AnalysisException("[UNRESOLVED_ROUTINE] Cannot resolve routine `sum_distinct` on search path [`system`.`builtin`, `system`.`session`, `spark_catalog`.`default`]. SQLSTATE: 42883")
```

### Why are the changes needed?
Bug fix.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?

Added new tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #8 from sarutak/fix-sum-distinct.

Authored-by: Kousuke Saruta <sarutak@amazon.co.jp>
Signed-off-by: Kousuke Saruta <sarutak@amazon.co.jp>